Document: electrolib
Title: Debian electrolib Manual
Author: <insert document author here>
Abstract: This manual describes what electrolib is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/electrolib/electrolib.sgml.gz

Format: postscript
Files: /usr/share/doc/electrolib/electrolib.ps.gz

Format: text
Files: /usr/share/doc/electrolib/electrolib.text.gz

Format: HTML
Index: /usr/share/doc/electrolib/html/index.html
Files: /usr/share/doc/electrolib/html/*.html
