Document: electrotest
Title: Debian electrotest Manual
Author: <insert document author here>
Abstract: This manual describes what electrotest is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/electrotest/electrotest.sgml.gz

Format: postscript
Files: /usr/share/doc/electrotest/electrotest.ps.gz

Format: text
Files: /usr/share/doc/electrotest/electrotest.text.gz

Format: HTML
Index: /usr/share/doc/electrotest/html/index.html
Files: /usr/share/doc/electrotest/html/*.html
